pangalink:
  image: viljaste/pangalink:latest
  hostname: pangalink
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - pangalinkdata
  environment:
    - SERVER_NAME=localhost
pangalinkdata:
  image: viljaste/data:latest
  hostname: pangalinkdata
  volumes:
    - /pangalink
